bug fix: removed redundant check of `esp_secure_boot_verify_signature`
```
/opt/Espressif/esp-idf/components/app_update/esp_ota_ops.c: In function 'esp_ota_set_boot_partition':
/opt/Espressif/esp-idf/components/app_update/esp_ota_ops.c:434:74: error: 'data' undeclared (first use in this function)
     esp_err_t ret = esp_secure_boot_verify_signature(partition->address, data.image_len);
                                                                          ^
/opt/Espressif/esp-idf/components/app_update/esp_ota_ops.c:434:74: note: each undeclared identifier is reported only once fo
```
The above error was caused while building with SECURE_BOOT flags, removed it as it is unnecceassry (and buggy - data not declared). The  `image_validate` function already checks for `esp_secure_boot_verify_signature`